[tool.pytest.ini_options]
addopts = """
    --log-cli-level=INFO
    --cov=analizers
    --cov=datagen
    --cov=utils
    --cov-report=term-missing
    --cov-report=xml"""
testpaths = ["test"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = false
