version: '3'

env:
  PYTHONPATH: '{{ .TASKFILE_DIR }}'

tasks:
  test:
    - echo $PYTHONPATH
    - coverage run -m pytest
    - coverage report

  deps:
    - python -m pip install -r requirements.txt

  format:
    - black -l 120 .
